/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c6c4d8",
        "on-primary-fixed": "#05006c",
        "primary": "#4244df",
        "on-secondary-container": "#0f238e",
        "on-surface": "#1b1b24",
        "on-tertiary-fixed": "#1c1148",
        "primary-container": "#5d61f9",
        "on-secondary-fixed-variant": "#2a3ba2",
        "on-error": "#ffffff",
        "on-background": "#1b1b24",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f2effc",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#2928ca",
        "surface-container-high": "#e9e6f3",
        "on-secondary-fixed": "#000e5f",
        "secondary-fixed-dim": "#bbc3ff",
        "on-error-container": "#93000a",
        "primary-fixed": "#e1e0ff",
        "surface-container": "#efecf9",
        "secondary": "#4454bb",
        "surface-container-highest": "#e4e1ee",
        "error": "#ba1a1a",
        "surface-bright": "#fcf8ff",
        "surface": "#fcf8ff",
        "on-tertiary-container": "#fffbff",
        "inverse-surface": "#302f39",
        "secondary-container": "#8393fe",
        "on-primary": "#ffffff",
        "outline": "#767587",
        "tertiary-container": "#766da8",
        "secondary-fixed": "#dfe0ff",
        "tertiary-fixed-dim": "#c9beff",
        "on-primary-container": "#fffbff",
        "surface-dim": "#dbd8e5",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-low": "#f5f2ff",
        "on-surface-variant": "#454555",
        "on-tertiary-fixed-variant": "#483f77",
        "background": "#fcf8ff",
        "tertiary": "#5d548d",
        "surface-variant": "#e4e1ee",
        "on-secondary": "#ffffff",
        "inverse-primary": "#c0c1ff",
        "tertiary-fixed": "#e6deff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#4547e1",
        "brand-tint": "#FFDBFD",
        "brand-accent": "#6367FF",
        "soft-accent": "#C9BEFF"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "24px",
        "xs": "4px",
        "md": "16px",
        "gutter": "16px",
        "base": "8px",
        "container-margin-mobile": "16px",
        "container-margin-desktop": "40px",
        "xl": "32px",
        "sm": "8px"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
